### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by AlexanderH15** [rbtl-fs24/md-03-assignments-AlexanderH15#1]
I had to add this manually?
library(usethis)
use_git_config(user.name = ...

@larnsce

**Comment by larnsce** [comment]
Thanks, @AlexanderH15. I do not understand why this setting doesn't translate between projects. It used to be fine, but something must have changed in the infrastructure. 

I have had a look at your code and it looks great. Well done. 👏🏼

I will close the issue now.
